version: '3.8'

services:
  # ProjectChimera 4-Layer System Orchestrator (Main Service)
  chimera-orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: chimera-orchestrator
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/app/src
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - chimera-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s
    command: ["python", "-m", "project_chimera.orchestrator_4layer"]
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Data Collectors Service (News + X Posts)
  data-collectors:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: chimera-data-collectors
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/app/src
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - chimera-network
    healthcheck:
      test: ["CMD", "python", "-m", "project_chimera.collectors.health_check"]
      interval: 120s
      timeout: 30s
      retries: 3
      start_period: 60s
    command: ["python", "-m", "project_chimera.collectors.main"]
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Development Trading Bot
  trading-bot-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: chimera-trading-bot-dev
    restart: "no"
    env_file:
      - .env.dev
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - /app/.venv  # Don't mount venv
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - postgres
    networks:
      - chimera-network
    profiles:
      - development

  # Redis for caching and message queues
  redis:
    image: redis:7-alpine
    container_name: chimera-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - chimera-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.1'

  # PostgreSQL for persistent storage
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: chimera-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-chimera}
      POSTGRES_USER: ${POSTGRES_USER:-chimera}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-chimera123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chimera-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-chimera}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: chimera-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - chimera-network
    profiles:
      - monitoring

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: chimera-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin123}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - chimera-network
    profiles:
      - monitoring

  # Nginx reverse proxy (production)
  nginx:
    image: nginx:alpine
    container_name: chimera-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - chimera-orchestrator
    networks:
      - chimera-network
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  chimera-network:
    driver: bridge