api_settings:
  news_api:
    base_url: "https://newsapi.org/v2/"
    endpoints:
      top_headlines: "everything"
    query_params:
      q: "USD JPY OR 為替 OR 外国為替"
      sortBy: "publishedAt"
      language: "ja"
  
  alpha_vantage:
    base_url: "https://www.alphavantage.co/query"
    function: "FX_DAILY"
    from_symbol: "USD"
    to_symbol: "JPY"
    outputsize: "compact"
    datatype: "csv"

  openai:
    model: "gpt-4-turbo"
    max_tokens: 1000
    temperature: 0.7

logging:
  level: "INFO"
  file_path: "./logs/app.log"